materials/urls.py
from django.urls import path
from . import views

app_name = 'materials'

urlpatterns = [
    path('', views.index, name='index'),
    path('materials/<slug:slug>/', views.materials, name='materials'),
    path('materials/<slug:slug>/recommendations/', views.recommendations, name='recommendations'),
    path('materials/<slug:slug>/<int:id>/', views.material_details, name='details'),
]

recommender_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('back-office/', admin.site.urls),
    path('', include('materials.urls', namespace='materials')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_, name='login'),
    path('logout/', views.logout_, name='logout'),
    path('profile/', views.profile, name='profile'),
    # path('search/', views.site.urls),
    # path('materials/<slug:title>/', views.site.urls),
    # path('materials/<slug:title>/recomendations/', views.site.urls),
    # path('materials/<slug:title>/<int:id>/', views.site.urls),
]

materials/models.py
from django.db import models
from django.utils.text import slugify
from django.core.validators import MaxValueValidator, MinValueValidator

from django.contrib.auth.models import User


class Material(models.Model):
    image = models.ImageField(max_length=500)
    title_original = models.CharField(max_length=255)
    description = models.CharField(max_length=5000)
    technical_description = models.CharField(max_length=2000)
    material_type = models.ForeignKey('MaterialType', on_delete=models.CASCADE)
    average_mark = models.FloatField(
        validators=[MinValueValidator(0), MaxValueValidator(5)],
        blank=True,
        null=True,
        db_index=True
    )
    redactor_mark = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(5)],
        blank=True,
        null=True,
        db_index=True
    )

    def __str__(self):
        return f'{self.title_original}'

    def calculate_average(self):
        pass

    def get_all_translates(self):
        pass


class MaterialTitleTranslate(models.Model):
    material = models.ForeignKey(Material, on_delete=models.CASCADE)
    language = models.CharField(max_length=32)
    translate = models.CharField(max_length=255)


    def __str__(self):
        return f'{self.material}-{self.language}'


class MaterialType(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, blank=True, db_index=True)
    description = models.CharField(max_length=5000)
    image = models.ImageField()
    counter = models.IntegerField()

    def calc_counter(self):
        pass

    def __str__(self):
        return f'{self.title}'


class RedactorReview(models.Model):
    material = models.ForeignKey(Material, on_delete=models.CASCADE)
    text = models.CharField(max_length=5000)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def get_author_full_name(self):
        pass

    def __str__(self):
        return f'{self.material} - {self.author}'


class Advertisement(models.Model):
    picture = models.ImageField()
    title = models.CharField(max_length=100)
    text = models.CharField(max_length=5000)
    reference = models.CharField(max_length=5000)
    material = models.ForeignKey(Material, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date_start = models.DateField()
    date_end = models.DateField()


    def __str__(self):
        return f'{self.material} - {self.title}'


class UserMark(models.Model):
    material = models.ForeignKey(Material, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    mark = models.IntegerField(
        models.FloatField(validators=[MinValueValidator(0), MaxValueValidator(5)]), db_index=True)
    is_from_fb = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.material} - {self.user}'


class UserComment(models.Model):
    material = models.ForeignKey(Material, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=5000)

    def __str__(self):
        return f'{self.material} - {self.user}'

materials/views.py
import pickle
from django.db.models import Avg
from django.views.generic import ListView, DetailView
from django.http import Http404
from materials import models
from users.models import FbInfo
from django.contrib.auth.models import User
import numpy as np

class MaterialTypesListView(ListView):
    model = models.MaterialType
    template_name = 'materials/types-list.html'
    paginate_by = 20

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.order_by('id')
        # return qs.filter(thread__account__owner=self.request.user, thread__account__is_active=True)


index = MaterialTypesListView.as_view()


class MaterialsListView(ListView):
    model = models.Material
    template_name = 'materials/list.html'
    paginate_by = 20

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(
            material_type__slug=self.kwargs.get('slug'),
        ).exclude(image='').exclude(average_mark__isnull=True)
        # print(qs[0].users_mark)
        return qs.order_by('-average_mark')


materials = MaterialsListView.as_view()


class RecommendationsView(ListView):
    model = models.Material
    template_name = 'materials/recomendations.html'
    paginate_by = 20

    def get_queryset(self):
        qs = super().get_queryset()
        all_movies = []
        with open('trained_model.pkl', 'rb') as tr_model:
            model = pickle.load(tr_model)
            materials = models.Material.objects.filter(material_type=1).order_by('id')[:10]
            vector = self.request.user.fbinfo.get_vector(materials)
            prediction = model.predict([vector,])
            cluster_center = model.data[prediction]
            print(f'Cluster center({prediction})={cluster_center}')
            labels = model.labels_
            class_members = labels == prediction
            # for i, obj in enumerate(model.data):
            #     if class_members[i]:
            #         print(obj)
            indexes = np.where(class_members==True)
            for i in indexes[0]:
                n = int(i)
                print(model.data[n])
                fb_info = FbInfo.objects.all().order_by('id')[n]
                print(fb_info.get_vector(materials))
                movies = models.UserMark.objects.filter(mark__gte=2, user=fb_info.user).\
                    values_list('material__id', flat=True)
                all_movies.extend(movies)
        qs = qs.filter(id__in=all_movies, average_mark__gt=3,
            material_type__slug=self.kwargs.get('slug')
        ).exclude(image='').exclude(average_mark__isnull=True)[:30]
        return qs


recommendations = RecommendationsView.as_view()


class LetterDetailView(DetailView):
    pk_url_kwarg = 'id'
    model = models.Material
    template_name = 'materials/details.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            user_mark = models.UserMark.objects.get(user=self.request.user,
                                                    material=self.object.id)
        except models.UserMark.DoesNotExist:
            user_mark = None
        context.update({
            'user_mark': user_mark
        })
        return context
    # def get_object(self, queryset=None):
    #     obj = super().get_object()
    #     if obj.thread.account.owner == self.request.user:
    #         return obj
    #     else:
    #         raise Http404('Letter does not exist!')


material_details = LetterDetailView.as_view()

materials/templates/materials/details.html
{% extends '_base.html' %}
{% block title %}
    <title>{{ object.title_original }}</title>
{% endblock title %}

{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'materials:index' %}">Домашня</a></li>
            <li class="breadcrumb-item " >
                <a href="{% url 'materials:materials' object.material_type.slug %}">
                    {{ object.material_type.title }}
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'materials:recommendations' object.material_type.slug %}">
                    Рекомендації
                </a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">{{ object.title_original }}</li>
        </ol>
    </nav>
{% endblock breadcrumb %}

{% block content %}
    <div class="container">
        <br/>
        <h2 class="text-center">{{ object.title_original }}</h2>

        <div class="card" >
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">

                        <img src="{% if 'http' in object.image.url %}
                                                    {{ object.image }}
                                                  {% else %}
                                                    {{ object.image.url }}
                                                  {% endif %}" alt="{{ object.slug }}"
                             class="rounded mx-auto d-block">
                        <hr/>
                        <h5>Ваша оцінка:
                            {% if user_mark %}
                                {% if user_mark.is_from_fb %}
                                    <b>5</b> (Оцінка взята з facebook <a href=""> Змінити)</a>
                                {% else %}
                                    <b>{{ user_mark.mark }}</b>
                                {% endif %}
                            {% else %}
                                <a href="#"><b>0</b></a>
                                <a href="#"><b>1</b></a>
                                <a href="#"><b>2</b></a>
                                <a href="#"><b>3</b></a>
                                <a href="#"><b>4</b></a>
                                <a href="#"><b>5</b></a>
                            {% endif %}
                        </h5>
                        {% if object.average_mark %}
                            <h5>Оцінка редактора: {{ object.redactor_mark }}</h5>
                        {% endif %}
                    </div>
                </div>
                <hr/>
                <div class="row">
                    <div class="col-md-6">
                        <h3 >Опис:</h3>
                        {{ object.technical_description|safe }}
                    </div>
                    <div class="col-md-6">
                        <h3 >Переклад:</h3>
                        {% for trans in object.materialtitletranslate_set.all %}
                            <p><b>{{ trans.language }}</b> - {{ trans.translate }}</p>
                        {% endfor %}
                    </div>
                </div>
                <hr/>
                <div class="row">
                    <div class="col-md-12">
                        <h3 >Сюжет:</h3>
                        {{ object.description|safe    }}
                    </div>
                </div>
                {#                <div class="row">#}
                {#                    <div class="col-md-12">#}
                {#                        {% if object.average_mark %}#}
                {#                            <h5>Оцінка користувачів: {{ object.average_mark }}</h5>#}
                {#                        {% endif %}#}
                {#                        {% if object.average_mark %}#}
                {#                            <h5>Оцінка редактора: {{ object.redactor_mark }}</h5>#}
                {#                        {% endif %}#}
                {##}
                {#                    </div>#}
                {#                </div>#}
            </div>
        </div>
    </div>

{% endblock %}

materials/templates/materials/list.html
{% extends '_base.html' %}
{% block title %}
    <title>Всі типи матеріалів</title>
{% endblock title %}

{% block content %}
    <a href="{% url 'materials:recommendations' page_obj.0.material_type.slug %}" type="button"
       class="btn btn-secondary btn-lg btn-block" style="color: #fff;">
        Переглянути цільові пропозицій в категорій "{{ page_obj.0.material_type.title }}"
    </a>
    <div class="container">
        <br/>

        <h2 class="text-center">Всі {{ page_obj.0.material_type.title }}</h2>
        <div class="row">
            {% for obj in page_obj %}
                <div class="col-md-6" style="margin-top: 30px">
                    <div class="card" style="background-color: #E8F8F5">
                        <div class="card-body">
                            <h3>{{ obj.title_original }}</h3>
                            <div class="row">
                                <div class="col-md-6">
                                    <a href="{% url 'materials:details' obj.material_type.slug obj.id %}">
                                        <img src="{% if 'http' in obj.image.url %}
                                                    {{ obj.image }}
                                                  {% else %}
                                                    {{ obj.image.url }}
                                                  {% endif %}"
                                             alt="{{ obj.slug }}"
                                             class="rounded mx-auto d-block" style="width: 100%">
                                    </a>
                                </div>
                                <div class="col-md-6">
                                    {{ obj.technical_description|safe    }}
                                    <hr/>
                                    <b>Оцінка користувачів: {{ obj.average_mark|floatformat }}</b>
                                    <br>
                                    <b>Оцінка редактора: {{ obj.redactor_mark }}</b>
                                </div>
                                {#                        <div class="col-md-6">#}
                                {#                            {{ obj.description|truncatechars:900|safe }}#}
                                {#                        </div>#}
                            </div>
{#                            <div class="row">#}
{#                                <div class="col-md-12">#}
{#                                    {% if obj.average_mark %}#}
{#                                        <h5>Оцінка користувачів: {{ obj.average_mark }}</h5>#}
{#                                    {% endif %}#}
{#                                    {% if obj.redactor_mark  %}#}
{#                                        <h5>Оцінка редактора: {{ obj.redactor_mark }}</h5>#}
{#                                    {% endif %}#}
{##}
{#                                </div>#}
{#                            </div>#}
                        </div>
                    </div>
                </div>
                <br/>

            {% endfor %}
        </div>
        {% if page_obj.has_previous or page_obj.has_next %}
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
                        <a class="page-link"
                           href="?page={% if page_obj.has_previous %}{{ page_obj.previous_page_number }}{% endif %}"
                           tabindex="-1">Previous
                        </a>
                    </li>
                    <li class="page-item active">
                        <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }} <span class="sr-only">(current)</span></a>
                    </li>

                    <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
                        <a class="page-link"
                           href="?page={% if page_obj.has_next %}{{ page_obj.next_page_number }}{% endif %}"
                           tabindex="-1">Next
                        </a>
                    </li>
                </ul>
            </nav>
        {% endif %}

    </div>
{% endblock %}

materials/templates/materials/recomendations.html
{% extends '_base.html' %}
{% block title %}
    <title>Всі типи матеріалів</title>
{% endblock title %}

{% block content %}
    <div class="container">
        <br/>

        <h2  class="text-center"    >Ваші цільові пропозиції:</h2>
        <P class="text-center">
            Ці пропозиції сформовані на основі вашого профілю у FB та діяльності в межах даного ресурсу.
            Щоб змінити перейдіть до <a href="">свого профілю</a>.
        </P>
        <div class="row">
            {% for obj in page_obj %}
                <div class="col-md-6" style="margin-top: 30px">
                    <div class="card" style="background-color: #E8F8F5">
                        <div class="card-body">
                            <h3>{{ obj.title_original }}</h3>
                            <div class="row">
                                <div class="col-md-6">
                                    <a href="{% url 'materials:details' obj.material_type.slug obj.id %}">
                                        <img src="{% if 'http' in obj.image.url %}
                                                    {{ obj.image }}
                                                  {% else %}
                                                    {{ obj.image.url }}
                                                  {% endif %}"
                                             alt="{{ obj.slug }}"
                                             class="rounded mx-auto d-block" style="width: 100%">
                                    </a>
                                </div>
                                <div class="col-md-6">
                                    {{ obj.technical_description|safe    }}
                                    <hr/>
                                    <b>Оцінка користувачів: {{ obj.average_mark|floatformat }}</b>
                                    <br>
                                    <b>Оцінка редактора: {{ obj.redactor_mark }}</b>
                                </div>
                                {#                        <div class="col-md-6">#}
                                {#                            {{ obj.description|truncatechars:900|safe }}#}
                                {#                        </div>#}
                            </div>
                            {#                            <div class="row">#}
                            {#                                <div class="col-md-12">#}
                            {#                                    {% if obj.average_mark %}#}
                            {#                                        <h5>Оцінка користувачів: {{ obj.average_mark }}</h5>#}
                            {#                                    {% endif %}#}
                            {#                                    {% if obj.redactor_mark  %}#}
                            {#                                        <h5>Оцінка редактора: {{ obj.redactor_mark }}</h5>#}
                            {#                                    {% endif %}#}
                            {##}
                            {#                                </div>#}
                            {#                            </div>#}
                        </div>
                    </div>
                </div>
                <br/>
            {% endfor %}
        </div>
        {% if page_obj.has_previous or page_obj.has_next %}
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
                        <a class="page-link"
                           href="?page={% if page_obj.has_previous %}{{ page_obj.previous_page_number }}{% endif %}"
                           tabindex="-1">Previous
                        </a>
                    </li>
                    <li class="page-item active">
                        <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }} <span class="sr-only">(current)</span></a>
                    </li>

                    <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
                        <a class="page-link"
                           href="?page={% if page_obj.has_next %}{{ page_obj.next_page_number }}{% endif %}"
                           tabindex="-1">Next
                        </a>
                    </li>
                </ul>
            </nav>
        {% endif %}

    </div>
{% endblock %}

materials/templates/materials/types-list.html
{% extends '_base.html' %}
{% block title %}
    <title>Всі типи матеріалів</title>
{% endblock title %}

{% block content %}

    <div class="container">
        <br/>
        <h2 class="text-center">Всі типи матеріалів</h2>
        <div class="row">
            {% for obj in page_obj %}
                <div class="col-md-6 mb-2">
                    <a href="{% url 'materials:materials' obj.slug %}">
                        <h2 class="text-center">{{ obj.title }} ({{ obj.material_set.count }})</h2>
                    </a>
                    <a href="{% url 'materials:materials' obj.slug %}">
                        <img src="{{ obj.image.url }}" alt="{{ obj.slug }}"
                             style="width: 300px; height: 300px" class="rounded-circle mx-auto d-block">
                    </a>

                </div>
                {% if forloop.counter0 == 1 %}
                    <div class="col-md-12">
                        <hr>
                    </div>
                {% endif %}
            {% endfor %}
        </div>

        {% if page_obj.has_previous or page_obj.has_next %}
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
                        <a class="page-link"
                           href="?page={% if page_obj.has_previous %}{{ page_obj.previous_page_number }}{% endif %}"
                           tabindex="-1">Previous
                        </a>
                    </li>
                    <li class="page-item active">
                        <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }} <span class="sr-only">(current)</span></a>
                    </li>

                    <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
                        <a class="page-link"
                           href="?page={% if page_obj.has_next %}{{ page_obj.next_page_number }}{% endif %}"
                           tabindex="-1">Next
                        </a>
                    </li>
                </ul>
            </nav>
        {% endif %}

    </div>

{% endblock %}