recommender_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('back-office/', admin.site.urls),
    path('', include('materials.urls', namespace='materials')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_, name='login'),
    path('logout/', views.logout_, name='logout'),
    path('profile/', views.profile, name='profile'),
    # path('search/', views.site.urls),
    # path('materials/<slug:title>/', views.site.urls),
    # path('materials/<slug:title>/recomendations/', views.site.urls),
    # path('materials/<slug:title>/<int:id>/', views.site.urls),
]

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
        <title>Mail Agent</title>
    {% endblock title %}

    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}" type="text/css" media="all">

    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>

    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/custom.css' %}" type="text/css" media="all">
</head>

<body>
    {% block nav %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="/">Recommender</a>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="">Новинки</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="">Анонси</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <div class=" active-purple-2 mr-3">
                          <input class="form-control" type="text" placeholder="Шукати" aria-label="Search">
                        </div>
                    </li>
                    <li class="nav-item">
                        {% if request.user.is_authenticated %}
                            <a class="navbar-text" href="{% url 'users:profile' %}">({{ request.user }})</a>
                        {% endif %}
                    </li>
                    <li class="nav-item">
                        {% if request.user.is_authenticated %}
                            <a class="nav-link" href="{% url 'users:logout' %}">Вийти</a>
                        {% else %}
                            <a class="nav-link" href="{% url 'users:login' %}">Увійти</a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </nav>
    {% endblock nav %}
    {% block breadcrumb %}
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Домашня</a></li>
          </ol>
        </nav>
    {% endblock breadcrumb %}
    <div id="content"  class="container-fluid">
        {% include 'messages_alert.html' %}
        {% block content %}

        {% endblock content %}
    </div>

    {% block extrascripts %}

    {% endblock extrascripts %}
    <br/>
    <br/>

    <footer class="page-footer  bg-dark pt-4" style="width: 100%">
    </footer>
</body>
</html>

templates/messages_alert.html
{% block messages %}
    <br/>
    {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    <span {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</span>
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                </div>
            {% endfor %}
    {% endif %}
{% endblock %}